name: custom_bot
channels:
- defaults
dependencies:
- python=3.8.13
- pip=21.0.1
- pip:
    - beautifulsoup4
    - requests
    - pandas
    - python-telegram-bot
    - selenium
    - lxml
    - html5lib

